# Generated by Django 5.2.5 on 2025-08-27 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('youtube_url', models.URLField(help_text='Paste a YouTube URL or ID')),
                ('youtube_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='core.agency')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='core.brand')),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CD', 'Creative Director'), ('CW', 'Copywriter'), ('AD', 'Art Director'), ('DIR', 'Director'), ('DOP', 'Director of Photography'), ('EDIT', 'Editor'), ('CLR', 'Colourist'), ('PM', 'Producer/PM'), ('VFX', 'VFX Lead')], max_length=24)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.ad')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='core.agency')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='core.person')),
            ],
            options={
                'ordering': ['ad_id', 'role', 'person__name'],
            },
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['youtube_id'], name='core_ad_youtube_d9a2fa_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['-year', 'title'], name='core_ad_year_7506af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='credit',
            unique_together={('ad', 'person', 'role')},
        ),
    ]
