# Generated by Django 5.2.5 on 2025-08-26 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('youtube_url', models.URLField(help_text='Paste a YouTube URL')),
                ('youtube_id', models.CharField(db_index=True, editable=False, max_length=20)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated', max_length=250)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='core.brand')),
            ],
            options={
                'ordering': ['-year', 'title'],
                'indexes': [models.Index(fields=['youtube_id'], name='core_ad_youtube_d9a2fa_idx')],
            },
        ),
    ]
