# Generated by Django 5.2.5 on 2025-08-26 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='core.agency'),
        ),
    ]
