# Generated by Django 5.2.5 on 2025-08-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agency_slug_brand_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='tags_m2m',
            field=models.ManyToManyField(blank=True, related_name='ads', to='core.tag'),
        ),
    ]
