# Generated by Django 5.2.5 on 2025-08-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_review_options_alter_review_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='credit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='person',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ad_credits', to='core.person'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.UniqueConstraint(fields=('ad', 'person', 'role'), name='uniq_ad_person_role'),
        ),
    ]
